FROM wordpress:latest
EXPOSE 80

# Set environment variables for WordPress
ENV WORDPRESS_DB_HOST='wordpress.cluster-cp80wyw4gk0z.us-west-2.rds.amazonaws.com'
ENV WORDPRESS_DB_USER='admin'
ENV WORDPRESS_DB_PASSWORD='Lg2103197878'
ENV WORDPRESS_DB_NAME='word_db'
#
